CREATE DATABASE courses_web;

\c courses_web;

CREATE TABLE "Users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "id_rol" int NOT NULL
);

CREATE TABLE "Courses" (
  "id_course" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20),
  "description" varchar(100),
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL
);

CREATE TABLE "Courses_Videos" (
  "id_course_video" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(300),
  "id_course" int NOT NULL
);

CREATE TABLE "Categories" (
  "id_category" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_category" varchar(20)
);

CREATE TABLE "Roles" (
  "id_rol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_rol" varchar(20)
);

CREATE TABLE "Levels" (
  "id_level" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_level" varchar(20)
);

CREATE TABLE "Teacher" (
  "id_teacher" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(20),
  "last_name" varchar(20)
);

CREATE TABLE "Users_category" (
  "id_user_category" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "id_category" int NOT NULL
);

CREATE TABLE "Categories_course" (
  "id_category_course" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_category" int NOT NULL,
  "id_course" int NOT NULL
);

ALTER TABLE "Users" ADD  CONSTRAINT FK_Users_Roles  FOREIGN KEY ("id_rol") REFERENCES "Roles" ("id_rol");

ALTER TABLE "Courses" ADD CONSTRAINT FK_Courses_Level FOREIGN KEY ("id_level") REFERENCES "Levels" ("id_level");

ALTER TABLE "Courses" ADD CONSTRAINT FK_Courses_Teacher FOREIGN KEY ("id_teacher") REFERENCES "Teacher" ("id_teacher");

ALTER TABLE "Courses_Videos" ADD CONSTRAINT FK_Courses_Videos_Courses FOREIGN KEY ("id_course") REFERENCES "Courses" ("id_course");

ALTER TABLE "Users_category" ADD CONSTRAINT FK_Users_Category_Categories FOREIGN KEY ("id_category") REFERENCES "Categories" ("id_category");

ALTER TABLE "Users_category" ADD CONSTRAINT FK_Users_Category_Users FOREIGN KEY ("id_user") REFERENCES "Users" ("id_user");

ALTER TABLE "Categories_course" ADD CONSTRAINT FK_Categories_Course_Categories FOREIGN KEY ("id_category") REFERENCES "Categories" ("id_category");

ALTER TABLE "Categories_course" ADD CONSTRAINT FK_Categories_Course_Courses FOREIGN KEY ("id_course") REFERENCES "Courses" ("id_course");

INSERT INTO "Roles" (name_rol) VALUES('Student'),('Teacher'),('Admin');	

INSERT INTO "Categories" (name_category) VALUES('Finance'),('Technology'),('Marketing');
jesi','jesi@gmail.com','123456',60,3);

INSERT INTO "Levels"(name_level) VALUES('Principiante'),('Medio'),('Avanzado');

INSERT INTO "Teacher"(first_Name,last_name) VALUES('Geovanny','SIerra'),('Roger,'Bravo'),('Victor','Medina');

INSERT INTO "Courses"(title,description,id_level,id_teacher) VALUES('CSS','Hojas de Estilo',1,1),('HTML','HTML',1,2),('JAVASCRIPT','JS',1,3),('REACT','REACT',2,2);

INSERT INTO "Courses_Videos"(url,id_course) VALUES('www.youtube.com/video1',1),('www.youtube.com/video2',2),('www.youtube.com/video3',3),('www.youtube.com/video4',4);

INSERT INTO "Categories_course"(id_category,id_course) VALUES(2,1),(2,2),(2,3),(2,4);

INSERT INTO "Users_category"(id_user,id_category) VALUES(1,2),(2,2);